-- =============================================
-- OneSpider Monitor — Complete Database Schema
-- =============================================
-- Run this ENTIRE file in Supabase SQL Editor
-- Fresh database setup — paste and click "Run"
-- All report views use IST (Asia/Kolkata)
-- =============================================


-- ═══════════════════════════════════════════════
-- STEP 1: MAIN TABLE
-- ═══════════════════════════════════════════════

-- Drop if exists (safe for re-runs)
DROP VIEW IF EXISTS quarterly_uptime_report CASCADE;
DROP VIEW IF EXISTS monthly_uptime_report CASCADE;
DROP VIEW IF EXISTS weekly_uptime_report CASCADE;
DROP VIEW IF EXISTS daily_uptime_report CASCADE;
DROP TABLE IF EXISTS uptime_logs CASCADE;

-- Core table: stores every health check result
CREATE TABLE uptime_logs (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    icmp_up     BOOLEAN NOT NULL,
    http_up     BOOLEAN NOT NULL,
    latency_ms  FLOAT DEFAULT 0,
    error_message TEXT
);

-- Add comment for documentation
COMMENT ON TABLE uptime_logs IS 'Stores infrastructure health check results every 5 minutes';
COMMENT ON COLUMN uptime_logs.icmp_up IS 'Whether ICMP ping was successful';
COMMENT ON COLUMN uptime_logs.http_up IS 'Whether HTTP request was successful';
COMMENT ON COLUMN uptime_logs.latency_ms IS 'Average ICMP ping latency in milliseconds';
COMMENT ON COLUMN uptime_logs.error_message IS 'Error details when check fails';


-- ═══════════════════════════════════════════════
-- STEP 2: INDEXES FOR PERFORMANCE
-- ═══════════════════════════════════════════════

-- Fast lookup: latest logs first
CREATE INDEX idx_logs_created_desc ON uptime_logs (created_at DESC);

-- Fast lookup: find downtime incidents
CREATE INDEX idx_logs_downtime ON uptime_logs (created_at DESC) 
    WHERE icmp_up = FALSE AND http_up = FALSE;


-- ═══════════════════════════════════════════════
-- STEP 3: ROW LEVEL SECURITY (RLS) & PUBLIC ACCESS
-- ═══════════════════════════════════════════════

-- Enable RLS (Supabase best practice)
ALTER TABLE uptime_logs ENABLE ROW LEVEL SECURITY;

-- 1. Allow service_role full access (for Node.js script insertions)
CREATE POLICY "Allow service role full access" ON uptime_logs
    FOR ALL USING (true) WITH CHECK (true);

-- 2. Allow PUBLIC (anon) read-only access (for public Status Page dashboard)
CREATE POLICY "Allow public read access" ON uptime_logs
    FOR SELECT USING (true);

-- 3. Grant table permissions to anon role
GRANT SELECT ON uptime_logs TO anon;


-- ═══════════════════════════════════════════════
-- STEP 4: SLA REPORT VIEWS (All IST-Aligned)
-- ═══════════════════════════════════════════════

-- ─── Daily Report ───────────────────────────────
-- Groups checks by IST day
CREATE OR REPLACE VIEW daily_uptime_report AS
SELECT 
    date_trunc('day', created_at AT TIME ZONE 'Asia/Kolkata') AS report_date,
    COUNT(*) AS total_checks,
    ROUND(
        (SUM(CASE WHEN icmp_up = TRUE OR http_up = TRUE THEN 1 ELSE 0 END)::numeric 
         / COUNT(*)::numeric) * 100, 2
    ) AS uptime_percentage,
    ROUND(AVG(latency_ms) FILTER (WHERE icmp_up = TRUE)::numeric, 2) AS avg_latency_ms,
    ROUND(MIN(latency_ms) FILTER (WHERE icmp_up = TRUE)::numeric, 2) AS min_latency_ms,
    ROUND(MAX(latency_ms) FILTER (WHERE icmp_up = TRUE)::numeric, 2) AS max_latency_ms,
    SUM(CASE WHEN NOT icmp_up AND NOT http_up THEN 1 ELSE 0 END) AS total_downtime_checks,
    SUM(CASE WHEN icmp_up = TRUE THEN 1 ELSE 0 END) AS icmp_success_count,
    SUM(CASE WHEN http_up = TRUE THEN 1 ELSE 0 END) AS http_success_count
FROM uptime_logs
GROUP BY 1 ORDER BY 1 DESC;


-- ─── Weekly Report ──────────────────────────────
-- Groups checks by IST week (Monday to Sunday)
CREATE OR REPLACE VIEW weekly_uptime_report AS
SELECT 
    date_trunc('week', created_at AT TIME ZONE 'Asia/Kolkata') AS report_week,
    COUNT(*) AS total_checks,
    ROUND(
        (SUM(CASE WHEN icmp_up = TRUE OR http_up = TRUE THEN 1 ELSE 0 END)::numeric 
         / COUNT(*)::numeric) * 100, 2
    ) AS uptime_percentage,
    ROUND(AVG(latency_ms) FILTER (WHERE icmp_up = TRUE)::numeric, 2) AS avg_latency_ms,
    ROUND(MIN(latency_ms) FILTER (WHERE icmp_up = TRUE)::numeric, 2) AS min_latency_ms,
    ROUND(MAX(latency_ms) FILTER (WHERE icmp_up = TRUE)::numeric, 2) AS max_latency_ms,
    SUM(CASE WHEN NOT icmp_up AND NOT http_up THEN 1 ELSE 0 END) AS total_downtime_checks,
    SUM(CASE WHEN icmp_up = TRUE THEN 1 ELSE 0 END) AS icmp_success_count,
    SUM(CASE WHEN http_up = TRUE THEN 1 ELSE 0 END) AS http_success_count
FROM uptime_logs
GROUP BY 1 ORDER BY 1 DESC;


-- ─── Monthly Report ─────────────────────────────
-- Groups checks by IST month
CREATE OR REPLACE VIEW monthly_uptime_report AS
SELECT 
    date_trunc('month', created_at AT TIME ZONE 'Asia/Kolkata') AS report_month,
    COUNT(*) AS total_checks,
    ROUND(
        (SUM(CASE WHEN icmp_up = TRUE OR http_up = TRUE THEN 1 ELSE 0 END)::numeric 
         / COUNT(*)::numeric) * 100, 2
    ) AS uptime_percentage,
    ROUND(AVG(latency_ms) FILTER (WHERE icmp_up = TRUE)::numeric, 2) AS avg_latency_ms,
    ROUND(MIN(latency_ms) FILTER (WHERE icmp_up = TRUE)::numeric, 2) AS min_latency_ms,
    ROUND(MAX(latency_ms) FILTER (WHERE icmp_up = TRUE)::numeric, 2) AS max_latency_ms,
    SUM(CASE WHEN NOT icmp_up AND NOT http_up THEN 1 ELSE 0 END) AS total_downtime_checks,
    SUM(CASE WHEN icmp_up = TRUE THEN 1 ELSE 0 END) AS icmp_success_count,
    SUM(CASE WHEN http_up = TRUE THEN 1 ELSE 0 END) AS http_success_count
FROM uptime_logs
GROUP BY 1 ORDER BY 1 DESC;


-- ─── Quarterly Report ───────────────────────────
-- Groups checks by IST quarter (Jan-Mar, Apr-Jun, Jul-Sep, Oct-Dec)
CREATE OR REPLACE VIEW quarterly_uptime_report AS
SELECT 
    date_trunc('quarter', created_at AT TIME ZONE 'Asia/Kolkata') AS report_quarter,
    COUNT(*) AS total_checks,
    ROUND(
        (SUM(CASE WHEN icmp_up = TRUE OR http_up = TRUE THEN 1 ELSE 0 END)::numeric 
         / COUNT(*)::numeric) * 100, 2
    ) AS uptime_percentage,
    ROUND(AVG(latency_ms) FILTER (WHERE icmp_up = TRUE)::numeric, 2) AS avg_latency_ms,
    ROUND(MIN(latency_ms) FILTER (WHERE icmp_up = TRUE)::numeric, 2) AS min_latency_ms,
    ROUND(MAX(latency_ms) FILTER (WHERE icmp_up = TRUE)::numeric, 2) AS max_latency_ms,
    SUM(CASE WHEN NOT icmp_up AND NOT http_up THEN 1 ELSE 0 END) AS total_downtime_checks,
    SUM(CASE WHEN icmp_up = TRUE THEN 1 ELSE 0 END) AS icmp_success_count,
    SUM(CASE WHEN http_up = TRUE THEN 1 ELSE 0 END) AS http_success_count
FROM uptime_logs
GROUP BY 1 ORDER BY 1 DESC;


-- ═══════════════════════════════════════════════
-- STEP 4.5: GRANT VIEW PERMISSIONS TO PUBLIC
-- ═══════════════════════════════════════════════
-- Views don't use direct RLS, they need to be granted permission explicitly
GRANT SELECT ON daily_uptime_report TO anon;
GRANT SELECT ON weekly_uptime_report TO anon;
GRANT SELECT ON monthly_uptime_report TO anon;
GRANT SELECT ON quarterly_uptime_report TO anon;

-- ═══════════════════════════════════════════════
-- STEP 5: AUTO-CLEANUP FUNCTION (Optional)
-- ═══════════════════════════════════════════════
-- Deletes logs older than 1 year to keep DB size in free tier
-- You can call this manually or set up a Supabase cron

CREATE OR REPLACE FUNCTION cleanup_old_logs()
RETURNS void AS $$
BEGIN
    DELETE FROM uptime_logs 
    WHERE created_at < NOW() - INTERVAL '1 year';
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

COMMENT ON FUNCTION cleanup_old_logs IS 'Removes logs older than 1 year to stay within Supabase free tier limits';


-- ═══════════════════════════════════════════════
-- STEP 6: ENABLE REALTIME (Optional)
-- ═══════════════════════════════════════════════
-- Uncomment below if you want to listen to live inserts
-- (useful if you build a dashboard later)

-- ALTER PUBLICATION supabase_realtime ADD TABLE uptime_logs;


-- ═══════════════════════════════════════════════
-- ✅ VERIFICATION: Run this after setup to confirm
-- ═══════════════════════════════════════════════

-- Check table exists
SELECT EXISTS (
    SELECT FROM information_schema.tables 
    WHERE table_name = 'uptime_logs'
) AS table_created;

-- Check all views exist
SELECT table_name AS view_name 
FROM information_schema.views 
WHERE table_schema = 'public' 
AND table_name LIKE '%uptime_report'
ORDER BY table_name;
